### ISSUE TITLE
Docker compose ports are overridden once container is deployed

### ISSUE THREAD

**Issue by tim-durrant** [linuxserver/docker-prowlarr#54]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The Prowlarr Web UI should listen on the port specified in the docker compose file.

### Expected Behavior

The Prowlarr Web UI configuration file overrides the port specified in the docker compose file.

### Steps To Reproduce

I want Prowlarr to listen on port 9697.  So in my docker compose, I have this:

`    ports:
      - 9697:9697
`

However once the docker container is deployed, it defaults to port 9696 in config.xml:

`<Port>9696</Port>`

I edited config.xml to be 9697 and Prowlarr was then accessible via the Web UI.

### Environment

```markdown
- OS:Ubuntu
```

### CPU architecture

x86-64

### Docker creation

```bash
prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /nas/config/prowlarr/config:/config
    networks:
      default:
        ipv4_address: 172.20.0.36
    ports:
      - 9697:9697
    restart: always
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 1.12.2.4211 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Debug] MigrationController: Took: 00:00:00.4218167 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:9697 
[Info] CommandExecutor: Starting 3 threads for tasks. 
[ls.io-init] done.
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/prowlarr/bin
```

**Comment by aptalca** [comment]
Map `9697:9696`, don't edit the config

**Comment by tim-durrant** [comment]
This is fine with just one instance of Prowlarr.  How would I edit the docker compose file for one Prowlarr listening on 9696 and a second Prowlarr listening on 9697?

**Comment by aptalca** [comment]
`9696:9696` on one and `9697:9696` on the other

https://github.com/linuxserver/docker-prowlarr?tab=readme-ov-file#parameters

**Comment by Radiotechniman** [comment]
I have the same issue, while the solution from @aptalca  works on a normal deploy, I need to have this run through gluetun
So this does not work because the 2nd instance of prowlarr will not receive any requests since 9696 catches all requests.

I was hoping for an environment flag like "-e PORT: 9697" 

-=edit=-

My workaround seems to work;

1. stop your 1st prowlarr (p1) instance
2. make a new folder in your */docker/ folder
3. copy the prowlarr docker-compose into a new one 
4. update the port to 9697:9696 and make sure to change the location to the new folder
5. start the second prowlarr (p2) instance 
6. open the webbrowser and in prowlarr (p2) go to settings>general
7. update the port to 9697 and save (and restart
8. wait a couple of minutes and stop the P2 container
9. update the docker compose from 9696:9697 to 9697:9697 
10. start P1 and P2
11. happiness
